In [1]:
import pandas as pd


df = pd.read_csv("C:/Users/MY PC/OneDrive/Desktop/retrain/Reviews.csv")

In [25]:
df = df.drop_duplicates()

In [26]:
df.shape

(568454, 10)

In [27]:
print(df.columns.tolist())

['Id', 'ProductId', 'UserId', 'ProfileName', 'HelpfulnessNumerator', 'HelpfulnessDenominator', 'Score', 'Time', 'Summary', 'Text']

In [28]:
df=df.drop(columns=['Id', 'ProductId', 'UserId', 'ProfileName', 'HelpfulnessNumerator', 'HelpfulnessDenominator','Time', 'Summary'])

In [29]:
print(df.columns.tolist())

['Score', 'Text']

In [30]:
df = df.rename(columns={"Text": "Review", "Score": "Rating"})
print(df.head())

   Rating                                             Review
0       5  I have bought several of the Vitality canned d...
1       1  Product arrived labeled as Jumbo Salted Peanut...
2       4  This is a confection that has been around a fe...
3       2  If you are looking for the secret ingredient i...
4       5  Great taffy at a great price.  There was a wid...

In [31]:
df = df.drop_duplicates()

In [32]:
rating_counts = df['Rating'].value_counts().sort_index()
rating_counts

Rating
1     36280
2     20804
3     29772
4     56074
5    250745
Name: count, dtype: int64

In [33]:
print("🔍 Checking for missing values...")
print(df.isnull().sum())

🔍 Checking for missing values...
Rating    0
Review    0
dtype: int64

In [34]:
# Display only the rows with missing values
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Rating, Review]
Index: []

In [35]:
df.head

<bound method NDFrame.head of         Rating                                             Review
0            5  I have bought several of the Vitality canned d...
1            1  Product arrived labeled as Jumbo Salted Peanut...
2            4  This is a confection that has been around a fe...
3            2  If you are looking for the secret ingredient i...
4            5  Great taffy at a great price.  There was a wid...
...        ...                                                ...
568449       5  Great for sesame chicken..this is a good if no...
568450       2  I'm disappointed with the flavor. The chocolat...
568451       5  These stars are small, so you can give 10-15 o...
568452       5  These are the BEST treats for training and rew...
568453       5  I am very satisfied ,product is as advertised,...

[393675 rows x 2 columns]>

In [37]:
df.head()

   Rating                                             Review
0       5  I have bought several of the Vitality canned d...
1       1  Product arrived labeled as Jumbo Salted Peanut...
2       4  This is a confection that has been around a fe...
3       2  If you are looking for the secret ingredient i...
4       5  Great taffy at a great price.  There was a wid...

In [38]:
# Check if any reviews are repeated
duplicate_reviews = df[df.duplicated(subset=['Review'], keep=False)]

print("🔍 Total duplicate reviews:", df.duplicated(subset=['Review']).sum())
duplicate_reviews.head()

🔍 Total duplicate reviews: 96

      Rating                                             Review
1791       1  I don't know why everyone loves these chips. T...
2806       2  When I first started to use IAMS Savory Sauce,...
4928       3  Buffalo Bills Premium Snacks<br /><br />I real...
5023       4  Good product! good price  fast shipping . need...
6000       5  A few years ago, my cat was diagnosed with foo...

In [39]:
df = df.drop_duplicates(subset=['Review', 'Rating'])
print("✅ Duplicates removed. New shape:", df.shape)

✅ Duplicates removed. New shape: (393675, 2)

In [40]:
# Check if any reviews are repeated
duplicate_reviews = df[df.duplicated(subset=['Review'], keep=False)]

print("🔍 Total duplicate reviews:", df.duplicated(subset=['Review']).sum())
duplicate_reviews.head()

🔍 Total duplicate reviews: 96

      Rating                                             Review
1791       1  I don't know why everyone loves these chips. T...
2806       2  When I first started to use IAMS Savory Sauce,...
4928       3  Buffalo Bills Premium Snacks<br /><br />I real...
5023       4  Good product! good price  fast shipping . need...
6000       5  A few years ago, my cat was diagnosed with foo...

In [41]:
df = df.drop_duplicates(subset=['Review', 'Rating'])
print("✅ Duplicates removed. New shape:", df.shape)

✅ Duplicates removed. New shape: (393675, 2)

In [43]:
# Remove duplicate reviews (keep only the first occurrence)
df= df.drop_duplicates(subset=['Review'], keep='first')

print("✅ All duplicate reviews removed.")
print("Remaining rows:", df.shape[0])

✅ All duplicate reviews removed.
Remaining rows: 393579

In [44]:
# Double-check that no duplicate reviews remain
print("🔍 Remaining duplicate reviews:", df.duplicated(subset=['Review']).sum())

🔍 Remaining duplicate reviews: 0

In [45]:
df.shape()

TypeError: 'tuple' object is not callable

In [46]:
df.shape

(393579, 2)

In [47]:
df.head()

   Rating                                             Review
0       5  I have bought several of the Vitality canned d...
1       1  Product arrived labeled as Jumbo Salted Peanut...
2       4  This is a confection that has been around a fe...
3       2  If you are looking for the secret ingredient i...
4       5  Great taffy at a great price.  There was a wid...

In [48]:
rating_counts = df['Rating'].value_counts().sort_index()
rating_counts

Rating
1     36275
2     20792
3     29754
4     56042
5    250716
Name: count, dtype: int64

In [64]:
import pandas as pd

df = df.copy()  # original dataset

# Step 1: Sample imbalanced dataset
target_counts = {
    1: 2500,
    2: 3750,
    3: 6250,
    4: 7500,
    5: 5000
}

sampled_dfs = []
for rating, count in target_counts.items():
    subset = df[df['Rating'] == rating]
    sampled = subset.sample(n=count, random_state=42,
                            replace=True if len(subset) < count else False)
    sampled_dfs.append(sampled)

imbalanced_df = pd.concat(sampled_dfs).sample(frac=1, random_state=42).reset_index(drop=True)

# Step 2: Create remaining dataset correctly
# Use merge with indicator to avoid index issues
remaining_df = df.merge(imbalanced_df, on=['Rating','Review'], how='outer', indicator=True)
remaining_df = remaining_df[remaining_df['_merge'] == 'left_only'].drop(columns=['_merge'])

# Save both datasets
imbalanced_path = r"C:/Users/MY PC/OneDrive/Desktop/retrain/reviews_imbalanced.csv"
imbalanced_df.to_csv(imbalanced_path, index=False)

remaining_path = r"C:/Users/MY PC/OneDrive/Desktop/retrain/reviews_remaining.csv"
remaining_df.to_csv(remaining_path, index=False)

print(f"✅ Imbalanced dataset shape: {imbalanced_df.shape}")
print(f"✅ Remaining dataset shape: {remaining_df.shape}")

✅ Imbalanced dataset shape: (25000, 2)
✅ Remaining dataset shape: (368579, 2)

In [66]:
df1=pd.read_csv(r"C:/Users/MY PC/OneDrive/Desktop/retrain/reviews_imbalanced.csv")
df2=pd.read_csv(r"C:/Users/MY PC/OneDrive/Desktop/retrain/reviews_remaining.csv")

In [67]:
import pandas as pd

# Load datasets
df1 = pd.read_csv(r"C:/Users/MY PC/OneDrive/Desktop/retrain/reviews_imbalanced.csv")
df2 = pd.read_csv(r"C:/Users/MY PC/OneDrive/Desktop/retrain/reviews_remaining.csv")

# Check overlap
overlap_reviews = set(df1['Review']).intersection(set(df2['Review']))

if len(overlap_reviews) == 0:
    print("✅ No overlapping reviews. Datasets are mutually exclusive.")
else:
    print(f"⚠️ Found {len(overlap_reviews)} overlapping reviews between the two datasets.")

✅ No overlapping reviews. Datasets are mutually exclusive.

In [68]:
df=pd.read_csv(r"C:/Users/MY PC/OneDrive/Desktop/retrain/reviews_imbalanced.csv")

In [69]:
import pandas as pd

# Load the dataset
df = pd.read_csv(r"C:/Users/MY PC/OneDrive/Desktop/retrain/reviews_imbalanced.csv")

# Find rows where 'Review' is NaN
nan_reviews = df[df['Review'].isna()]

# Show count and examples
print(f"Total reviews with NaN text: {nan_reviews.shape[0]}")
print(nan_reviews.head())

Total reviews with NaN text: 0
Empty DataFrame
Columns: [Rating, Review]
Index: []

In [70]:
import pandas as pd

# Load dataset
df = pd.read_csv(r"C:/Users/MY PC/OneDrive/Desktop/retrain/reviews_imbalanced.csv")

# Filter reviews with Rating 3
rating_3_reviews = df[df['Rating'] == 3]

# Print all review texts and their ratings
for index, row in rating_3_reviews.iterrows():
    print(f"Rating: {row['Rating']}, Review: {row['Review']}")

Rating: 3, Review: I used this for a month, but not sure that it really helps me. When my baby started to burp up milk, I stopped using it to eliminate the cause. I have not gone back to using the fenugreek because I now have more milk than when I was taking the fenugreek. Hence, I am not sure whether this helps or not, but I would not discourage people from using it since many of my friends have used it with successful.
Rating: 3, Review: So I've been looking for this cereal literally every time I go to the store ever since I had it at boot camp 5 months ago. I went to about 4 to 5 different stores all with no success, also none of the store associates from any of the stores knew what I was talking about. Least to say, I was extremely happy to see that I could order my dream cereal on here. The product description does say that its 50 oz. however, for some reason I thought I would receive a much bigger bag for the price of $17.47. The cereal, like I remember it, is very good and my boyfriend agrees that it is the best cereal he has ever had, but sadly after 5 months of searching I wont be ordering this cereal again. The price is way too steep and its simply not worth the price. I will wait for the price to fall before ordering.
Rating: 3, Review: The product is good but one three of the bags were some how opened and got the mix everywhere once we open the box. Good product though....
Rating: 3, Review: I found the flavor to be very unusual: almost tobacco-like. The beans are oily, take a little longer to grind manually because they slip so much. Not sure I will order again. Going back to Reggie's Roast.
Rating: 3, Review: The texture is great and I suppose if you like mango syrup you would like these too.  Taste exactly like it.  A little too sweet for my taste.  The chocolate covered black liquorice is one I usually get, and those are awesome. But they ran out so I decided to give the mango and green apple a try.
Rating: 3, Review: I love peas, but I don't love these. I found them a little bland, to be honest, and the texture is just like Cheetos. Better for me than salted peanuts though!
Rating: 3, Review: I've fallen in love with other Earnest Eats Food Bars so I was excited to try out this flavor.  However, I was kind of disappointed - the taste is okay but not for me.  I found it to be too heavy on the cinnamon and while I couldn't really taste the ginger when eating the bar - it definitely left a funny aftertaste.
Rating: 3, Review: I really like coffee, but overall I would rate this as "okay" tasting - it is very strong, and has a bit of a bite in the flavoring that made me get a piece of gum to get the taste out of my mouth.  After a couple of sips, I was done and would rate it a 3 out of 5 stars.<br /><br />I opened this can up in the office, and passed around small sampler cups to my co-workers to get their thoughts as I work with several coffee connoisseurs.  Three women and one man said they thought it was good, and the three women would rate it a 4 on a 5 scale while the man said he would rate it a 3..<br /><br />Another man who typically buys and enjoys the Starbucks canned beverages said he would rate it a 3 out of 5 stars.<br /><br />Including myself, none of the test subjects hated it but everyone said the same thing - while they thought it was good, none of them believed it was "good enough" to make them want to go out and purchase some.  When I asked why, they had the same impression I had in that the coffee place downstairs was better none of us were really compelled to add this to our regular routines and shopping lists.<br /><br />One thing to note is there is a lot of sugar in this 6.4 ounce can: 10g!  The sugar and the caffeine combined should give you a little kick in the afternoon if that is what you are seeking.
Rating: 3, Review: I enjoyed this roast.  The subtle flavors of the mocha and nuts were nice and a little different then the coffee I had been drinking.  I would purchase this again.
Rating: 3, Review: Bustelo would be my second choice.  Instead, I would recommend trying<br />Mayorga Organic Cafe Cubano.  Mayorga will ship to you. Their beans<br />are nice, fresh, dark and oily.  Great strong coffee.
Rating: 3, Review: I bought this item for it's meal replacement abilities and it does just that- thus the 3 stars. The negative side is that you won't want to eat anything at all after you drink this mix. It took me a few days to realize what it tastes like and I've come to the conclusion that it tastes like vomit. Yes, vomit. I tried the mix in orange juice, water, blueberry juice, cran-grape juice, and both with and without fruits but the taste it the same. It leaves a distinct taste in your mouth that is nearly impossible to get rid so I can only suggest time for the taste to disappear. When drinking the powder, be aware that as you near the end of the drink, you may find tiny flakes that are nearly impossible to avoid regardless of how long you mix the drink. This drink mix has left me gassy and nauseas but since I paid over $30 for the container (which last about 2 weeks when using 1 scoop a day), I'll continue to drink it until it's gone but never again will I buy it. I'm going for pills next time because the taste of this drink mix is sickening but yes, it does replace a meal just as it suggests.
Rating: 3, Review: My items came in great condition, but instead of the hard red winter wheat I got Spring wheat. Go figure.
Rating: 3, Review: As I reported when I received my order, it was supposed to be in a pack of 12, well someone needs to send me the other two packs as I only received 10, so I will not be ordering this item from here anymore, I will be taking my business elsewhere.
Rating: 3, Review: cool idea but the item was poorly packaged and the cover of the set was stained with spices that had leaked out of their containers. Since this is a food item, it should have been completely sealed and not only were the individual spice containers not sealed, but the box came in a non-sealed plastic bag. Also, the kit was a bit smaller than I was anticipating (I guess not entirely a bad thing) AND the ratio of mixed spices (like "italian seasoning", "mexican seasoning", etc) to pure spices was a little dissapointing - I would have liked to get more pure spices.
Rating: 3, Review: I love this orange juice so much. This juice is ''from concentrate'' which most people would say is lower quality. I personally like ''FROM Concentrate'' The Best.<br /><br />TWO THINGS I would like to point out are that<br />Costco sells these for 1/3 of the price of amazon.<br />also most of the orange juice comes from BRAZIL....so despite the great taste i would say to drink these sparingly and opt for the Florida's natural which contains 100 percent Florida oj for sure.
Rating: 3, Review: If you have a "gulper" please be VERY careful with this product!!!  Please supervise your pets with this treat, as the pieces are VERY small and I can see may present a choking hazard or cause internal blockage for some dogs.  I have a 14lb pooch who is a self regulator (ie. wont wolf down her food all at once, but graze here and there.) and have no issues with food or toys; meaning even if she has a nice juicy steak in her mouth, I can easily get it right out of her mouth with not even much of a protest.  She also knows the leave it command, and will drop stuff for me to get away from her.<br /><br />Despite those facts, I am still pretty leery of given her these..."just in case."  But my dog is my baby... so she only gets it when I am right there with her and can supervise, and I make sure she is actually chewing them.<br /><br />The variety is nice, and the smell isnt as bad as some bull's stick, or hooves or whatever on the market.  Also, the ingredients are all natural, which is important to me.<br /><br />However, I worry too much about the pieces being so small....so despite the fact that she likes 'em (she is a very picky eater.) This will probably be the one and only time I will purchase this product.
Rating: 3, Review: In terms of taste, its a bit bland, but it seems if I combine this with a bit of meat, say, smoked sausage or some such, it becomes a bit more palatable.  its also an "acquired taste" that takes a bit of getting used to, but the chewiness factor is probably the reason for it being an acquired taste. Still, worth trying once, since everyone has different tastes... I wouldnt be so sure about buying this again, though even though its not bad as a lunch prep
Rating: 3, Review: This is a nice smooth coffee, a part of the Keurig K-cup portfolio. This is labelled "extra bold." Not sure that that is the case. This has a nice smooth, albeit rather mild (and even bland) flavor.<br /><br />However, some K-cups have a harsh, almost acidic, quality to them and are not particularly pleasant. This produces a nice cup of coffee.
Rating: 3, Review: All of the bars are of course past the expiration date. It doesn't affect the taste, but makes the bars break apart easily.
Rating: 3, Review: This coconut egg was good, but not as good as the ones I used to get as a child.  I thought it was expensive for the size. Think it would have been better covered in dark chocolate.
Rating: 3, Review: In the process of trying to find a nice bottle of Balsamico for my brother-in-law, I came across the following nice discussion of Balsamic Vinegars:<br />[...]<br /><br />You read, you decide. The label clearly states that this vinegar is 30 years old - no argument there. However, it is listed as a "condimento", which is an unregulated designation typically ascribed to younger balsamicos.<br /><br />Hey- if you've got enough spare cash, buy a bottle of this and a bottle of a "Tradizionale" (say, a gold Modeno or a silver Reggio Emilia) and provide a review.<br /><br />Me? I can't afford two -- and probably wouldn't buy one at all if it wasn't a gift for my foodie bro'-in-law.....<br /><br />This might be a stellar vinegar. But how does it compare with <a href="http://www.amazon.com/gp/product/B0014EMI2E">Traditional Aged Balsamic of Reggio Emila 24 Year Argento Silver</a> or <a href="http://www.amazon.com/gp/product/B001YIRHOY">Affinato, Aceto Balsamic Tradizionale di Modena DOP</a>?<br /><br />Beats me....
Rating: 3, Review: Tastes good if I mix it with some lemonade to get some tartness, otherwise tastes like an herbal scent bag.
Rating: 3, Review: This coffee is ok, but I wish they could make a decaf and half caf that had the flavor of regular coffee. It sort of has a slight maple taste to it.
Rating: 3, Review: I'm definitely a hearts of palm snob. I look for (in this order) consistency of texture, taste, and price. The best palm i n the world is SunPix, from Costa Rica, but Costco has stopped carrying it, so life is a quest for the next best. This product, also from Costa Rica, is entirely satisfactory, and I will buy it again . . . at least until Amazon (or someone) makes SunPix available to me.
Rating: 3, Review: I have a basic Cuisinart espresso machine that I normally use with Starbucks espresso pods. I saw the Illy tin at Wegman's and decided to give them a shot (no pun intended). Unfortunately, what I discovered is that these pods -- as is -- do not work with my espresso machine. The resulting shot looked like tea. I was somewhat annoyed as the tin doesn't say much of anything that is helpful, but what I eventually tried was cutting the excess portion of the wrapper off so that it looked exactly like a Starbucks pod. It worked perfectly and produced a great shot with lots of crema.<br /><br />I am drinking my latte now, and while it is good, I wouldn't say it is any better than my normal Starbucks-pod lattes. As the Starbucks pods are much cheaper (and easier), I'll be sticking with those after this tin.
Rating: 3, Review: I gave the product 5 stars in an earlier review and am updating it. I was looking at the product I received from Amazon, which was placed at the doorstep in a hot sunny day. I asked myself if I've researched into the plastic used. Glad to know that it doesn't contain BPA. Recycling #7 can be good or bad plastic. I've read that it's best to go with #1, #2, #4 and #5 plastics. So I decided to err on the safe side. I am giving this a 3-star because it's probably not a big deal but since I know about it, I don't want to live with that uncertainty that I may be harming my baby.<br /><br />Previous review:<br />My baby ate 5 tiny spoons of it the first time he tried the peas. After that, it kinda got boring for him and then I mixed it in with his cereal, and he ate it all. I would describe the taste as non-offending. It is neither sweet nor sour and is mild tasting to be one of the first foods to introduce.<br />I had thought the product would contain only organic peas and water, but it has more (like tuna oil etc.). I guess that's alright. We use quite a few vegetables and fruits from Earth's Best and I think it's good to offer different brands.
Rating: 3, Review: Kellogg's Crunchy Nut cereal doesn't come packaged as a kids' breakfast item, but it sure was a hit with the under-10 crowd in my house.  One bowl revealed the reason why:  it bears a striking resemblance to Frosted Flakes.  The crunchy nut aspect of the cereal comes from tiny nut bits on the flakes themselves, not from any sort of separate clusters.  For that reason, their appearance is actually hit-or-miss from bite to bite.  However, that sweetness is in every spoonful, and if you're not searching for a lot of that flavor, then this may not be the cereal for you.  It's strange to me that the box gives the impression of a wholesome, possibly even healthy cereal and yet the taste is pure kids' Saturday morning treat.
Rating: 3, Review: These are a good candy for children that need to be on all natural diets.  If eaten plain, they are no match for M&Ms.  They worked well in monster cookies, however.  At least, I thought so.  My husband and children did not agree with me, however.  I think these are an excellent alternative if some of the artificial flavors and colors found in other candy do not agree with you (or you don't agree with them).
Rating: 3, Review: These crackers are made by Back to Nature Foods located in Madison, WI--made in the USA! I give these crackers 4/5 for flavor, 5/5 for texture, 5/5 for maintaining Earth conscious integrity, 0/5 for truth in labeling--score 3.5<br /><br />The carton is made of 100% recycled paperboard and the ink is derived from vegetables. The company supports the Nature Conservancy (Protecting nature, preserving life).<br /><br />These are crispy wheat crackers with a sweet and mild flavor.  These are super crispy crackers that will hold up to any dip or topping.<br /><br />The sweetness adds just enough flavor to make your toppings pop.  I personally serve them with fish dips (salmon) and cheese toppings--yummy!<br /><br />The crackers are made of unbleached enriched flour and contain wheat flour, niacin, reduced iron, thiamine mononitrate (vitamin B1), riboflavin (vitamin B2), folic acid, safflower oil, raw sugar, defatted wheat germ, cornstarch, brown rice syrup, sea salt, malted barley extract, leavening (monocalcium phosphate, baking soda), natural turmeric flavor.<br /><br />The 8 oz package contain 8 servings--17 crackers.  Each serving contains 130 cal., 4 g fat, .5 g polyunsaturated fat, 2.5 g monounsaturated fat, 230 mg sodium, 55 mg potassium, 22 g carbs, 1 g fiber, 4 g sugars, 2 g protein.<br /><br />The package states that the crackers contain no artificial perservatives or flavors and no hydrogenated oils.  However, the product does contain Thiamine mononitrate which is a 'synthetic form' of vitamine B1, and medical and nutrition experts recommend a daily potassium intake of 4.7 g per/day.<br /><br />Don't forget to recycle the box!
Rating: 3, Review: I have only had my machine for about a month but I ordered the 3 pack of these vanilla latte macchiato because I kept adding vanilla flavoring to the cappuccino drinks.  I had very high expectations for these and I was disappointed.  My favorite drink is a skinny vanilla latte from Starbucks but these taste nothing like it.  They do have a weird processed vanilla flavor to them.  I LOVE the cappuccino drinks for the dolce gusto machine.  Don't order these if you want a vanilla flavored drink, just order the cappuccinos and some different flavorings to add to them.  My boyfriend, whose idea of coffee is QuikTrip Cappuccino loaded with sugar, likes these with a couple tablespoons of sugar dumped in.
Rating: 3, Review: Bought this hoping for a great deal.  Didn't realize that the packets are pretty small.  If you wait for a sale at your grocery store, you can get a better deal.  Not by much though, if it matters to you.
Rating: 3, Review: Not necessarily a bad thing, but this cacao is quite sour. If you're used to the Dutch process chocolate and expect the similar mild-to-bitter chocolate flavor, you'll be unpleasantly surprised by the acidic taste.
Rating: 3, Review: I bought these cookies because they were rated #1 by Consumer Reports magazine, which calls them "tender".  Ha!<br /><br />If you like dark, thin, crispy cookies, then these are for you.  However, I'm a thick and chewy type of cookie gal, so these aren't the best tasting cookies, IMHO.<br /><br />To be more objective, I would say that they are baked a wee bit (1 minute?) too long.  Some people--my husband being one, but then again, he likes burnt toast!--like overbaked cookies. Not me.<br /><br />I saw his two cookies each had one chocolate chip. I checked my two--one of which<br />I put back in the package after I decided I don't like Tate's--and my remaining cookie also had one chip.  Dang!
Rating: 3, Review: It adds a smoky flavor to food but doesn't taste like bacon to me.  The baconaise is good but same thing, it doesn't taste like bacon just smoky.  All in all its a good product but i was disappointed  that it didn't taste any more like bacon than it did after all I had read and heard about it.
Rating: 3, Review: I thought this would be a "chunky" type dog food since it is part of the description; but, it was ground. The dogs were not loving this and they had really loose stools.
Rating: 3, Review: If you are a baker you will know the difference between good and bad vanilla paste, this paste is a good product just a little pricy.  It's hard to judge what 4 oz is, not very much, 3 stars for the price.
Rating: 3, Review: These candies have a great flavor, but they don't last very long.  They look like SweetTarts, only they're not as well compressed as SweetTarts are.  If you carry them around in your pocket, you'll probably have a lot of powder left in the tin when you eat the last one.  I'm still looking for a really good sugar-free candy without artificial sweeteners.  This one is close, but I think I'll keep looking.
Rating: 3, Review: Guys, do you know what "malossol" means in Russian?<br />"Lightly salted".<br />This particular caviar was actually over-salted quite a bit.<br />Other than that its a very good tasting caviar (I guess you can blame a puddlefish for that), very close to Russian Sturgeon's caviar.
Rating: 3, Review: I bought these because my vet recommended them for my dog's teeth. I honestly don't know what to rate them as far as how effectively they are reducing her tartar build up. I used to always give her bully sticks, but she developed a bladder stone and she can no longer have those. She is 4 pounds and one of these chews lasts her about 5 or 10 minutes, which is disappointing. A bully stick will last her a few hours. If you are looking for a chew to occupy your dog for more than a few minutes, go for something else. I will keep purchasing this product however becuase my dog loves them and they are recommended by my vet.

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

In [71]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import nltk

In [72]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess(text):
    tokens = text.lower().split()                 # lowercase + tokenize
    tokens = [w for w in tokens if w.isalpha()]  # keep only words
    tokens = [w for w in tokens if w not in stop_words]  # remove stopwords
    tokens = [lemmatizer.lemmatize(w) for w in tokens]   # lemmatization
    return " ".join(tokens)

In [73]:
df['Cleaned_Text'] = df['Review'].astype(str).apply(preprocess)

# Check the cleaned text
df[['Review','Cleaned_Text']].head()

,Review,Cleaned_Text
0,"I used this for a month, but not sure that it ...",used sure really help baby started burp stoppe...
1,You can't tell this from the wheat brands. Mix...,tell wheat mix make wonderful moist sometimes ...
2,So I've been looking for this cereal literally...,looking cereal literally every time go store e...
3,This sauce is excellent. Medium hot with smoky...,sauce medium hot smoky undertone distinctive g...
4,"Although this cocoa is called Special Dark, it...",although cocoa called special special dark coc...

In [74]:

df.columns

Index(['Rating', 'Review', 'Cleaned_Text'], dtype='object')

In [75]:

df = df.drop(columns=['Review'])

# Check remaining columns
df.columns

Index(['Rating', 'Cleaned_Text'], dtype='object')

In [76]:

df = df.rename(columns={'Cleaned_Text': 'Review'})


df.columns

Index(['Rating', 'Review'], dtype='object')

In [77]:
df.columns

Index(['Rating', 'Review'], dtype='object')

In [78]:
# Remove any leading/trailing spaces in column names
df.columns = df.columns.str.strip()

# Check columns again
print(df.columns)

Index(['Rating', 'Review'], dtype='object')

In [80]:
# Print first 20 reviews with Rating 3
print(rating_3_reviews.head(6250))

       Rating                                             Review
0           3  I used this for a month, but not sure that it ...
2           3  So I've been looking for this cereal literally...
5           3  The product is good but one three of the bags ...
9           3  I found the flavor to be very unusual: almost ...
12          3  The texture is great and I suppose if you like...
...       ...                                                ...
24984       3  I was expecting a really spectacular cup of te...
24986       3  The coffee is very good, but it seems the pric...
24991       3  I was delighted to discover this product whils...
24993       3  I've tried quite a few of this Switch juice dr...
24994       3  I grew up with Kool Aid, during an era where y...

[6250 rows x 2 columns]

In [81]:
print(df.isna().sum())

Rating    0
Review    0
dtype: int64

In [82]:
from sklearn.model_selection import train_test_split

# Ensure column names have no extra spaces
df.columns = df.columns.str.strip()

# Features and target
X = df['Review']
y = df['Rating']

# Stratified train-test split (80%-20%)
X_train_text, X_test_text, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Verify class distribution in train and test sets
train_counts = y_train.value_counts().sort_index()
test_counts  = y_test.value_counts().sort_index()

train_percent = y_train.value_counts(normalize=True).sort_index() * 100
test_percent  = y_test.value_counts(normalize=True).sort_index() * 100

print("=== Training Set Distribution ===")
print(pd.DataFrame({'Count': train_counts, 'Percentage': train_percent}))

print("\n=== Testing Set Distribution ===")
print(pd.DataFrame({'Count': test_counts, 'Percentage': test_percent}))

=== Training Set Distribution ===
        Count  Percentage
Rating
1        2000        10.0
2        3000        15.0
3        5000        25.0
4        6000        30.0
5        4000        20.0

=== Testing Set Distribution ===
        Count  Percentage
Rating
1         500        10.0
2         750        15.0
3        1250        25.0
4        1500        30.0
5        1000        20.0

In [83]:
# Check NaN values in X_train_text and X_test_text
print("NaN values in X_train_text:", X_train_text.isna().sum())
print("NaN values in X_test_text :", X_test_text.isna().sum())

# Check NaN values in y_train and y_test
print("NaN values in y_train:", y_train.isna().sum())
print("NaN values in y_test :", y_test.isna().sum())

NaN values in X_train_text: 0
NaN values in X_test_text : 0
NaN values in y_train: 0
NaN values in y_test : 0

In [84]:
# Combine X_test_text and y_test into a single DataFrame
test_df = pd.DataFrame({
    'Review': X_test_text,
    'Rating': y_test
})

# Filter rows where Rating == 3
rating_3_test = test_df[test_df['Rating'] == 3]

# Print all reviews with Rating 3
for i, row in enumerate(rating_3_test.itertuples(), 1):
    print(f"{i}. Rating: {row.Rating}, Review: {row.Review}")

1. Rating: 3, Review: great price becoming harder harder find local like full many graham cracker kid love disappointment eighth package crumbled little ship
2. Rating: 3, Review: description balsamic indeed valuable review fails note unlike fine also grows ever one nip unfit drive put know going may able withstand effect heady take note two year shelf two enough oxygen undoubtedly penetrated turn vinegar good fine aged blend vein two buck use sparingly use buy slightly cheaper burning
3. Rating: 3, Review: product sweet qualify real baby nutrition many carbs ingredient pouch bpa free also good pouch easy squeeze could choking hazard baby pouch would good qualifier quick carb boost casual jogger used pouch would easy flatten pack back home properly dispose cap nice sweet good fun meal thriled role nutritious baby
4. Rating: 3, Review: using brand dog food two appears good dog problem additional amount paid delivered saturday monday still receive refund expedited delivery return amend
5. Rating: 3, Review: prefer bolder coffee compare doughnut shop k cup people rave cup wow factor sell local supermarket try pack buy
6. Rating: 3, Review: confirmed hamburger helper curious see velveeta good dethrone helping comfort food first say ultimate cheeseburger skillet dinner taste remarkably like real going beyond offering noodle ground hint ketchup mustard among tantalizing big fan hamburger stopped mustard taste much eight huge fan meat loved ate first helping time second rolled spice mixture getting overpowering bit scrapped noodle ate rest ground spice mix something made want keep eating happily try velveeta hamburger helper one quite hit spot way
7. Rating: 3, Review: like buck said rather nice rather underwhelming liked sourish taste well enough though hoping something mostly sardine like stray piece two mussel least veggie provided fairly decent almost four dollar
8. Rating: 3, Review: ordered pecan shortbread cooky excellent found almost every cookie careful packaging strongly recommend product gluten
9. Rating: 3, Review: like bakery parmesan flavored pita parmesan taste plain pita chip good like garlic flavored chip way felt like ate raw garlic clove tongue actually gave three star rating texture chip best ever outside restaurant taste much better pita former
10. Rating: 3, Review: ultra tiny paying pack really worth somewhat crispy chocolaty hoping melty chocolate finding one two per every cookie part melted onto wrapper one fun trying way
11. Rating: 3, Review: bought decoration fragrance sensitive chemical fragrance always looking natural give cinnamon
12. Rating: 3, Review: bar flavor easy travel folk celiac far best suffer dryness somewhat artificial problem almost never
13. Rating: 3, Review: fellow reviewer said something remember clear flavored coffee par flavor injected whatever ground coffee mask mediocre also said better buy good quality coffee add yield much better cup series purchase many flavored coffee wish would followed sound advice millstone cinnamon hazelnut ground package poorest lot far taste quality drink first get rid always try save best last far flavor slightly best long become expert definite taste lower expectation buy pure etc want flavor cup coffee add maybe use sort flavored average
14. Rating: 3, Review: matcha tried teavana matcha went creamy smooth nice light flavor without much also savory taste lingers palate liked read couple review teavana version quite real deal bit got much better real matcha ran teavana matcha already craving drove local whole food bought republic tea great tea opened canister product sealed inside foiled envelope snap inspected powder found chalky feel darker green sage tint seem like authentic found mixing powder dissolve well using bamboo whisk make matcha flavor bitterness vegetal thin ding enough experience brand read others experience teavana left bit say flavor bad regular green tea taste except much continue use product give calm yet alert feel got previous brand complaining decent looking steer clear powdered green tea
15. Rating: 3, Review: absolutely loved pretzel pepper baked right pretzel little tasty messy overly really fan line flavored broken pretzel although little better need try making black pepper version sure
16. Rating: 3, Review: enjoy coffee think provide excellent however tell blend purchased pack based another customer review impression getting kona big disappointment opened box received italian french say please let customer know box
17. Rating: 3, Review: flavorful snack satisfy craving looking try noi product yum flavor bland give prop
18. Rating: 3, Review: cooky okay grocery store cooky made good nestle tollhouse field better unrecognizable brand one might buy gas filling surrounded chocolate within cookie make contrasting texture soft chocolate shell gooey chip ahoy quite different better prefer chip ahoy
19. Rating: 3, Review: first got pup loved thought perfect size petite small pup exactly pound right hard find chew actually enjoy able hold tiny dingo actually priced decently amazon complaint really hard find cheap good great able chew minute hour depending end trying hide give family alone thing like chicken dyed think necessary make dingo stand long pup smell also chicken actually appealing rawhide try buying bag pork chomp skin chicken seemed like interested pork chomp twist dingo make bag also say product made bit buy pork chomp twist usually last less minute also cost going stick daily dingo ritual give pork chomp twist special occasion like holiday might switch better alternative really want continue feed stitch rawhide red hopefully find something better daily ritual
20. Rating: 3, Review: bought two year old many food bought hoping would like stop sneaking kid seems prefer cheerio oat taste notice good quick snack tends like corn flake
21. Rating: 3, Review: title say peanut butter variety cookie pretty much cookie offered girl scout peanut butter flavor strong chocolate predominate flavor mild peanut butter flavor nearly strong pb flavor peanut butter cup base cookie thin chocolate cookie nicely roughly half thin single oreo whole cookie half height big fan much care fairness wife daughter love huge comment pretty tagalong less peanut butter
22. Rating: 3, Review: sausage type flavor making doesnt quite hold round eat lot orgran falafel mix fantastic food hamburger mix although ff sodium reason harmony valley seems salty usually salt food go bag harmony valley may may order would lilke try hamburger vegetarian beggar cant real meat much cheaper kill animal animal kill subjugate
23. Rating: 3, Review: maybe way many perhaps spoiled best super boring
24. Rating: 3, Review: pretty good like rescue foster cat come
25. Rating: 3, Review: update recent shipment amount percent loss can badly dented libby excellent product stop sneaking badly dented can thru amazon order great always proof processing dented can amazon unknowingly sell every shipment date dented can severely case rendering product edible per case carrot wrap send amazon severely mark wrapper suggesting sealing warehouse sale amazon customer like quality taste product exception quality first nasty carrot top end top thru libby cannery surprised knowing canning process knew contaminated product longer ordering libby canned good sale stop sneaky tactic sending dented can proved shipping way grocery store law dented can go excellent soup stew plain heated excellent snack one watching drained pas salad
26. Rating: 3, Review: know happened upon bad box cereal bowl bowl question mind say little saddened visible absence chocolate piece half way literally poured plate see one substantial piece found find chocolate pebble mean small pebble consumed granola really granola pleasant flavor like almond excited bit chocolate luck cascadian farm make nice product granola cereal appears potential granola almond aware second ingredient cereal sugar follow rule ingredient never sugar
27. Rating: 3, Review: pleasant would prefer ginger like milder would excellent
28. Rating: 3, Review: one way know either since mister turkey love friskies turkey jumped away bowl reason quite funny keep mind persian might chicken turkey variety seems palatable looking good one recommend one recommend sure taste prior purchasing
29. Rating: 3, Review: oil lighter flavor still good biggest problem can shipping individual packaged ordered different oil can first shippment can order can intent give away course condition able want oil personal use mean order
30. Rating: 3, Review: year grew white hulless propcorn discovered product point could hold candle home since grow lot wanted purchase product similar quality purchased india tree paloma blanca popcorn good quality better store purchased white purchase product think expensive looking try brand less triple planting next
31. Rating: 3, Review: agree reviewer want bigger less wasted packaging presumably better
32. Rating: 3, Review: bought mother think ok good kona bought think worth favorite found remember
33. Rating: 3, Review: using coffee past far wish came ground instead whole like bitter taste
34. Rating: 3, Review: purchased mushroom intent grinding use rice mix aware must washed using making useless plan use cannot return
35. Rating: 3, Review: much better tim horton real chalkie taste hard mix straight
36. Rating: 3, Review: good put list get first
37. Rating: 3, Review: stuff bad know eat spoon spoon really good caviar without toast point cracker roe sprinkling fish morning egg caesar pretty
38. Rating: 3, Review: get small amount candy large look elsewhere product cheaper
39. Rating: 3, Review: coffee good every often pod put ground point pour pod
40. Rating: 3, Review: three loved one dog chew gulp cut greenies smaller portion help clean caused think look another product teeth
41. Rating: 3, Review: mint good worth price paid plus ridiculous shipping really someone looking freshen breath like overpriced candy really want
42. Rating: 3, Review: definitely strong coffee bitter taste instead bold coffee would purchase simply like would probably great someone serious need waking job
43. Rating: 3, Review: like tim stuff tasted pretty wondering contained caffeine find information expected mix chocolate coffee heavily slanted chocolate taste like cup hot bought hot chocolate rate ok
44. Rating: 3, Review: bought box cereal couple month eating second whole family seem like
45. Rating: 3, Review: earlier model rope instead rubber dog able get food little rubber thing middle quite effectively block food dog give used eat whole meal everyday old disappointed changed
46. Rating: 3, Review: founded wife located called master gelatos olive oil pumpkin spice rich see around thanksgiving company egg nog holiday amoretti sell around holiday favorite shipping low get free price range plan purchase xmas gift retired buy month get favorite customer service dept amazon add b prater okc ok drinking almost every day add thought need pumpkin less p c
47. Rating: 3, Review: allowed get expansive store least got
48. Rating: 3, Review: asian cup n noodle full flavor super problem get lobster flavor good thing still tasted
49. Rating: 3, Review: claim balsamic vinegar year vinegar designation mean must least year gold designation reserved balsamicos least year look alot like one also sold amazon fewer traditional balsamic vinegar looking something go silver gold good article full bought specific product specific could year guessing like old balsamico
50. Rating: 3, Review: another review mentioned passing tea stand gone half case even though different calorie seems sweet sure would love extra fact much like sweetened tea vinegar essence quite bad way get started kombucha replace gt better brand floating certainly better kombucha
51. Rating: 3, Review: nothing really wrong certainly appears maybe expecting much powdered soup although purchased tastier split pea soup know much vegan really care maybe like expect food like substantial look
52. Rating: 3, Review: item great alternative energy drink shippped item pack box item inside bigger small box opened transit item still drinkable hard pack box
53. Rating: 3, Review: little gaggia illy espresso machine illy espresso work illy pod iperespresso capsule dark roasted iperespresso capsule medium roasted like flavor illy favorite still nespresso line coffee citz espresso silver saw distributing illy immediately thought might nice cold drink early commute morning pulled two can frig drank drove tasted coffee can nothing like make home espresso richness illy make medium dark coffee can like medium bottom coffee taste exactly feared coffee canned two flavor sampled like cappuccino better caffe issimo coffee can think cappuccino work better caffe cold cappuccino went quickly aftertaste quite even finishing second coffee caffe without could still taste lowfat milk used sweetness espresso sugar can made coffee taste bit notice bitterness either aware size large soda pop narrow cappuccino inch taller caffe mention trouble finding place set console space large would wedge somehow keep everything else buy coffee drink sacrifice flavor really time evening put together bottle iced coffee morning cappuccino bad like sweet coffee like milk cappuccino bad even though extra time think try find time build iced coffee realized pleasant cold coffee drink long canned coffee
54. Rating: 3, Review: bar look delicious scrumptious spec seem less per granola cereal box taste better familiar kind pale taste full one feel eating especially thing eat put body contain many especially hard pronounce even know
55. Rating: 3, Review: price good fact organic good color unpleasant brown apricot dry stewed minute water squeeze lemon much palatable really flavorful pretty apricot would buy grocery hoping organic would
56. Rating: 3, Review: chunk granola fine want eat like granola want eat piece way big emptied bag onto cutting board chopped smaller helped messy piece flying everywhere taste good mind size like
57. Rating: 3, Review: item arrived day time ordered received consider price item expensive price chocolate plus shipping walmart item would known walmart got would bought
58. Rating: 3, Review: transaction smooth received product best ever still definitely would shop
59. Rating: 3, Review: big macadamia lover generally mauna loa make best product saw amazon chocolate macadamia jumped chance purchase wonderful unfortunately particular chocolate macadamia covered much sweet milk chocolate obliterates taste uploaded picture able find customer image top item nut covered quarter inch plus side chocolate pretty similar flavor symphony line since mine well go symphony bar almond toffee instead lot understand may exactly people searching think covered would preferred much lighter hopefully picture help guide buyer know
60. Rating: 3, Review: thought water though experience bitter found quite refreshing easier drink tap bottled water sore also said like water felt better going priced similarly bottled might consider purchasing
61. Rating: 3, Review: coffee brewed however love nice strong cup found coffee weak looking midrange would recommend trying like need something coffee
62. Rating: 3, Review: ordered enjoyed curry find used golden curry past make never found mild variety ordered along tried mild hardly even curry term like extremely thick sort bad hardly worth picking fan japanese go something higher unless got kid around sensitive something like
63. Rating: 3, Review: looking unsalted pretzel try limit love used live pa could get since moving able find disappointed bag piece another reviewer mentioned really craving pretzel hoping snyders fixed problem shipping
64. Rating: 3, Review: assume people would buy respect parent loved certainly fun walk memory lane said another looking dollar amount maybe five dollar candy box look full full black ribbon paper candy inside jostle looking box even way full take paper see much candy actually star idea definitely make great honestly could assemble something like presentation worth money well pick one
65. Rating: 3, Review: better competing brand green long starbucks decided jump keurig taste close extra bold intensity flavor get therefore worth higher still going try sumatra house blend place little personal favorite still house
66. Rating: 3, Review: tried stuff palm oil palm oil extremely contributes clearcutting rainforest rainforest action network personally committed buying item palm going try different
67. Rating: 3, Review: pretty good drink however barely taste ginger strong strong drink suprising lemon really like ginger would recommend like ginger expecting nice bad would
68. Rating: 3, Review: high quality tried grocery store oolong stated box like oolong try thing like peppery zesty like smooth flavor black doubt many like tea high flavor preference
69. Rating: 3, Review: vet recomended get rawhide love last forever give worst fart
70. Rating: 3, Review: two three cat turned nose flavor pill used conceal tapeworm pill half careful medicine residue hand sealed one cat gobbled two cat decided give grief ended get pill another love idea product impossible tell cat go try
71. Rating: 3, Review: fruit snack reason mix weird taste get little bit little friend ate fine see maybe bad batch glad got good deal irritated would paid like much better far really gummy never happen fruit
72. Rating: 3, Review: although purchased mixed nut flavor detectible mixed nut one got maybe quarter almond quite disappointed entire bar sesame seed flax fine ordered original impressed company fact bar gluten soy dairy also decent amount flavor little somewhat basically like raw sesame seed syrup nut flavor finish box purchased unless company decides actually put nut good effort therefore get
73. Rating: 3, Review: love believe best sardine one one spain pretty bought made made inferior quality compared definitely big drop flavor purchase last buy
74. Rating: 3, Review: best brownie company cheaper ingredient make lesser ticked etc paying big product lower quality shame still
75. Rating: 3, Review: according marketing kashi chocolate chip chewy snack banana bread taste dark chocolate like bar also touch natural natural goodness see suggests kellogg may going bit far making comparison banana first bite one feel soft slice banana bread fig softer probably less chewy typical oatmeal raisin chewing note along small chunk chocolate rolled tasting banana flavor almost overpower less identifiable memorable know bitterness lot prominent taste best selling point high carb content low protein content going win bar many plus made whole moderately high fiber content little fat low calorie count feature packaging make bottom edible much fun
76. Rating: 3, Review: make decent root quite deep flavorful would expect natural root beer using recommended mix taste adding compensate personal preference sassafras deeper beat majority big brand flavor hold
77. Rating: 3, Review: product totally reminds lipton lemon ice really really make good sleep relaxation

In [85]:
import pandas as pd

# Combine X_train_text and y_train into a single DataFrame
train_df = pd.DataFrame({
    'Review': X_train_text,
    'Rating': y_train
})

# Combine X_test_text and y_test into a single DataFrame
test_df = pd.DataFrame({
    'Review': X_test_text,
    'Rating': y_test
})

# Save the datasets
train_path = r"C:/Users/MY PC/OneDrive/Desktop/retrain/Imb_train_data.csv"
test_path  = r"C:/Users/MY PC/OneDrive/Desktop/retrain/Imb_test_data.csv"

train_df.to_csv(train_path, index=False)
test_df.to_csv(test_path, index=False)

print(f"✅ Training dataset saved at {train_path} with shape {train_df.shape}")
print(f"✅ Testing dataset saved at {test_path} with shape {test_df.shape}")

✅ Training dataset saved at C:/Users/MY PC/OneDrive/Desktop/retrain/Imb_train_data.csv with shape (20000, 2)
✅ Testing dataset saved at C:/Users/MY PC/OneDrive/Desktop/retrain/Imb_test_data.csv with shape (5000, 2)

In [86]:
df= pd.read_csv(r"C:/Users/MY PC/OneDrive/Desktop/retrain/Imb_train_data.csv")
df= pd.read_csv(r"C:/Users/MY PC/OneDrive/Desktop/retrain/Imb_test_data.csv")

In [2]:
import pandas as pd

# Load datasets
df= pd.read_csv(r"C:/Users/MY PC/OneDrive/Desktop/retrain/Imb_train_data.csv")
df= pd.read_csv(r"C:/Users/MY PC/OneDrive/Desktop/retrain/Imb_test_data.csv")

# Check for NaN values in train dataset
print("=== NaN values in Train Dataset ===")
print(train_df.isna().sum())
print(f"Total NaN values in Train Dataset: {train_df.isna().sum().sum()}\n")

# Check for NaN values in test dataset
print("=== NaN values in Test Dataset ===")
print(test_df.isna().sum())
print(f"Total NaN values in Test Dataset: {test_df.isna().sum().sum()}")

=== NaN values in Train Dataset ===

NameError: name 'train_df' is not defined

In [3]:
import pandas as pd

# Load datasets
train_df = = pd.read_csv(r"C:/Users/MY PC/OneDrive/Desktop/orginal/Imb_train_data.csv")
test_df  = pd.read_csv(r"C:/Users/MY PC/OneDrive/Desktop/retrain/Imb_test_data.csv")

# Check for NaN values in train dataset
print("=== NaN values in Train Dataset ===")
print(train_df.isna().sum())
print(f"Total NaN values in Train Dataset: {train_df.isna().sum().sum()}\n")

# Check for NaN values in test dataset
print("=== NaN values in Test Dataset ===")
print(test_df.isna().sum())
print(f"Total NaN values in Test Dataset: {test_df.isna().sum().sum()}")

=== NaN values in Train Dataset ===
Review    1
Rating    0
dtype: int64
Total NaN values in Train Dataset: 1

=== NaN values in Test Dataset ===
Review    0
Rating    0
dtype: int64
Total NaN values in Test Dataset: 0

In [4]:
import pandas as pd

# Load training dataset
train_df = pd.read_csv(r"C:/Users/MY PC/OneDrive/Desktop/retrain/Imb_train_data.csv")

# Replacement text for missing 4-star review
replacement_review = "good service and satisfactory experience"

# Replace the missing review where Rating == 4
train_df.loc[train_df['Review'].isna() & (train_df['Rating'] == 4), 'Review'] = replacement_review

# Verify replacement
missing_after = train_df[train_df['Review'].isna() & (train_df['Rating'] == 4)]
print(f"Number of missing 4-star reviews after replacement: {len(missing_after)}")

# Save the cleaned dataset in the same folder as original
cleaned_file_path = r"C:/Users/MY PC/OneDrive/Desktop/orginal/Imb_train_data.csv"
train_df.to_csv(cleaned_file_path, index=False)
print(f"✅ Cleaned training dataset saved at: {cleaned_file_path}")

Number of missing 4-star reviews after replacement: 0
✅ Cleaned training dataset saved at: C:/Users/MY PC/OneDrive/Desktop/orginal/Imb_train_data.csv

In [ ]:
= pd.read_csv(r"C:/Users/MY PC/OneDrive/Desktop/orginal/Imb_train_data.csv")